### ISSUE TITLE
clearLinks() method doesn't compile

### ISSUE THREAD

**Issue by TrudAX** [milnet92/MXTXppInterpreter#1]
Can you please check the issue with the following code, why it doesn't compile?

```
PurchLine   purchLine;
PurchLineForeignTradeCategory categoryLink;
QueryBuildDataSource qbdsLink;

QueryBuildDataSource aa;

aa.clearLinks();

qbdsLink.clearLinks();
categoryLink.initFromPurchLine(purchLine);
```

![image](https://github.com/user-attachments/assets/e1ff95b3-ebbe-428a-9236-e417dc11f415)

**Comment by milnet92** [comment]
The issue was related to static type checking, It should be fixed now with 8f7bad6. The "expectReturn" parameter on the variable parsing was not correctly passed to the subsequent variables / functions.

The code bellow will now pass the grammar check but fail the execution due to variables not being initialized.
![image](https://github.com/user-attachments/assets/4da207ac-417d-4f2b-a90e-5bca40290f8b)

**Comment by TrudAX** [comment]
Thanks for quick response @milnet92, it works now. 
I actually tested all may cases for "job" like tasks, they all worked perfectly, will try to describe them later.
Just wonder, what is your plan for this tool? It is great that you provide it under MIT, probably worth to create some GitHub sponsorship :)
Do you interested in some improvements, I can describe them in details, e.g. it will be useful to have some "jobs" template, editor undo button etc..

**Comment by milnet92** [comment]
My vision for this tool is to provide a mechanism to quickly:

- LEARN: Learning curve can be shortened as the time it took to execute in standard is way more
- FIX: Execute small scripts in DEV or Tier2+ environments
- IMPROVE: If you are an X++ developer, include this as your development process. No need to execute queries, or look up for labels, classes etc, just execute whatever you want here. You have to update or create some testing data? MXT. You want to quickly find out what method should you use? MXT. The list goes on...
- DIAGNOSTICS: With the debug capabilities, you can quickly diagnose either performance or bugs you way have. It's not perfect, but It provides a way to examine the operations that are being executed in a more flexible way.
