### ISSUE TITLE
build error of "Class 'MXTXppUnaryOperationProxy' does not implement the method 'BinaryNegate' from the interface 'XppInterpreter.Interpreter.Proxy.IXppUnaryOperationProxy'"

### ISSUE THREAD

**Issue by SamehSamirGit** [milnet92/MXTXppInterpreter#10]
After building the model , I got the below error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Class 'MXTXppUnaryOperationProxy' does not implement the method 'BinaryNegate' from the interface 'XppInterpreter.Interpreter.Proxy.IXppUnaryOperationProxy'.		C:\AOSService\PackagesLocalDirectory\Bin\XppSource\MXppTools\AxClass_MXTXppUnaryOperationProxy.xpp	3

**Comment by milnet92** [comment]
Solved with 83b21b2
