### ISSUE TITLE
x++ local function support

### ISSUE THREAD

**Issue by vukisz** [milnet92/MXTXppInterpreter#15]
So Class declarations are not supported. That means no methods, right?
Then Is there a way to define x++ local functions? I tried a couple of variations of local function, but it is not working :-)

**Comment by milnet92** [comment]
Local function declarations are **experimental**. They are a bit buggy at the moment, however you can experiment a bit with them.

![image](https://github.com/user-attachments/assets/16f64866-6c2d-4986-9729-82cc919bd32a)
Debugging local functions is also supported.

Please, report any issue regarding functions if possible, thanks!
