### ISSUE TITLE
Improvement: add a log that populates when a user press Execute

### ISSUE THREAD

**Issue by TrudAX** [milnet92/MXTXppInterpreter#3]
As the tool can be used to modify data, a possible improvement would be adding a simple log table (and a form to view it) that populates each time a user presses the Execute script button. 
Like a simple table with fields (created date time, userid, script text)

As the execution may be done a lot of time, also add a simple cleanup dialog to this form(but the "cleanup event" should be inserted in the same log)

**Comment by milnet92** [comment]
I actually though about it some time ago and I ended up with a design like you suggested
* What code was executed -> Soure code
* When was executed -> Created date and time
* Who executed the script -> User ID
* In which context was executed -> Parameters used to execute the script (was it with enforced ttsabort?)
* What was the "result" -> Infolog output and unhandeled exceptions
* What was the source of the execution -> (this I have my doubts of being useful) Batch, Script or future we services

I'll try to have something soon regarding this, or feel free to pull request youself
