### ISSUE TITLE
Improvements: Build action

### ISSUE THREAD

**Issue by FH-Inway** [milnet92/MXTXppInterpreter#32]
Using [FSC-PS for GitHub](https://github.com/fscpscollaborative/fscps), a build action could be set up that would first build the XppInterpreter .NET project and then use the resulting .dll to build the MXppTools module.

The build action would be triggered by pull requests (based on who the pull requester is, a manual approval step may be necessary before the action runs) or it can be triggered manually by the repository maintainers.

See the [build action](https://github.com/ameyer505/D365FOAdminToolkit/actions/runs/10477645507) of the D365FOAdminToolkit for a similar setup.

**Comment by milnet92** [comment]
That is SO cool, thank you!  I will 100% setup this as soon as I can. Also, thank you for providing an actual implementation example.

**Comment by FH-Inway** [comment]
To avoid this issue going stale, I created #37 for it.
See https://github.com/FH-Inway/MXTXppInterpreter/actions/runs/10870888527 for a sample run. The pull request also wants to execute the build action, but that needs to be approved first.

**Comment by milnet92** [comment]
Thank you @FH-Inway for the PR!
