### ISSUE TITLE
Auto-save script when press Execute

### ISSUE THREAD

**Issue by TrudAX** [milnet92/MXTXppInterpreter#39]
A couple of times hit this, when playing with something and then forgot to press Save
Is it possible to auto Save the script before the user presses Execute? (optionally to make it as a parameter, but it should be enabled by default, so the parameter should be something "Disable save on Execute")

**Comment by milnet92** [comment]
I like the idea! I think this also should apply only for the scripts already created because when you just want to test something quickly you go directly to the Editor without creating a script first, if that make sense?

**Comment by TrudAX** [comment]
yes, just like in Visual Studio. When you press Execute, the class is automatically saved(I don't even think the parameter is needed)

**Comment by milnet92** [comment]
Implemented in 769a4b7.

**Comment by TrudAX** [comment]
@milnet92 works perfectly, thanks
