### ISSUE TITLE
Dates parsing error- Character not recodnized 

### ISSUE THREAD

**Issue by TrudAX** [milnet92/MXTXppInterpreter#41]
I got the following error when running this job. It looks correct, so the expected result - it should be processed correctly

![image](https://github.com/user-attachments/assets/6bfd6cca-6c10-4daf-88d4-482c123de264)

```
TransDate d1;

d1 = 2\3\2024;

print d1; 

```

**Comment by milnet92** [comment]
Should be fixed with the provided PR.

![image](https://github.com/user-attachments/assets/ec9d1e0d-4585-4a2f-b22c-1327a1717d59)

**Comment by TrudAX** [comment]
thanks for the fix, works perfectly
